import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PurchaseRequestStatus, Role } from "@prisma/client";
import { prisma } from "../src/lib/prisma";
import { autoSuggestReplenishment, sweepLowStockAlerts } from "../src/lib/reminders";
import { api, TestContext, TEST_PREFIX, uid, type TestUser } from "./helpers/fixtures";

/**
 * Bölüm AI (8. tur): Otomatik stok yenileme önerisi.
 * - kritik + tedarikçi geçmişi → isAutoGenerated PENDING talep (miktar: son talep)
 * - bekleyen talep varken tekrar tarama → yeni talep YOK (dedup)
 * - tedarikçi geçmişi yok → talep yok
 * - tarama yalnızca kapsamlı (onlyProductIds) çağrılır — asla global.
 * - Temizlik: ürün/tedarikçi/talepler ID ile silinir.
 */
describe("Otomatik ikmal önerisi", () => {
  const ctx = new TestContext();
  let owner: TestUser;
  let token: string;
  let supplierId: string;
  let withHistoryId: string;
  let noHistoryId: string;
  const requestIds: string[] = [];

  beforeAll(async () => {
    owner = await ctx.createUser(Role.OWNER);
    token = await ctx.tokenFor(owner);

    const supplier = await prisma.supplier.create({ data: { name: `${TEST_PREFIX}Tedarikçi ${uid()}` } });
    supplierId = supplier.id;
    ctx.track("supplier", supplierId);

    const withHistory = await prisma.product.create({
      data: { name: `${TEST_PREFIX}Kritik ${uid()}`, unit: "L", currentStock: 2, criticalThreshold: 5 },
    });
    withHistoryId = withHistory.id;
    const noHistory = await prisma.product.create({
      data: { name: `${TEST_PREFIX}Geçmişsiz ${uid()}`, unit: "L", currentStock: 1, criticalThreshold: 5 },
    });
    noHistoryId = noHistory.id;

    // Geçmiş: tedarikçili, RECEIVED bir talep (tedarikçi geçmişi sayılır, PENDING değil).
    const past = await prisma.stockPurchaseRequest.create({
      data: { productId: withHistoryId, quantity: 25, supplierId, status: PurchaseRequestStatus.RECEIVED, requestedByUserId: owner.id, receivedAt: new Date() },
    });
    requestIds.push(past.id);
  });

  afterAll(async () => {
    await prisma.stockPurchaseRequest.deleteMany({ where: { OR: [{ id: { in: requestIds } }, { productId: { in: [withHistoryId, noHistoryId] } }] } });
    await prisma.product.deleteMany({ where: { id: { in: [withHistoryId, noHistoryId] } } });
    await ctx.cleanup();
  });

  it("kritik + tedarikçi geçmişi → isAutoGenerated PENDING talep açılır (son tedarikçi/miktar)", async () => {
    const created = await sweepLowStockAlerts([withHistoryId, noHistoryId]);
    expect(created).toBeGreaterThanOrEqual(0);

    const auto = await prisma.stockPurchaseRequest.findMany({ where: { productId: withHistoryId, status: PurchaseRequestStatus.PENDING } });
    expect(auto).toHaveLength(1);
    expect(auto[0].isAutoGenerated).toBe(true);
    expect(auto[0].supplierId).toBe(supplierId);
    expect(Number(auto[0].quantity)).toBe(25);
    expect(auto[0].requestedByUserId).toBeTruthy();

    // Listede rozet için alan döner
    const list = await api().get("/products/purchase-requests?status=PENDING&limit=100").set("Authorization", `Bearer ${token}`);
    expect(list.status).toBe(200);
    const row = list.body.data.find((r: { id: string }) => r.id === auto[0].id);
    expect(row?.isAutoGenerated).toBe(true);
  });

  it("bekleyen talep varken tekrar tarama → yeni talep açılmaz (dedup)", async () => {
    await sweepLowStockAlerts([withHistoryId]);
    expect(await autoSuggestReplenishment(withHistoryId)).toBeNull();
    const pending = await prisma.stockPurchaseRequest.count({ where: { productId: withHistoryId, status: PurchaseRequestStatus.PENDING } });
    expect(pending).toBe(1);
  });

  it("tedarikçi geçmişi olmayan kritik ürün → talep yok", async () => {
    expect(await autoSuggestReplenishment(noHistoryId)).toBeNull();
    const count = await prisma.stockPurchaseRequest.count({ where: { productId: noHistoryId } });
    expect(count).toBe(0);
  });

  it("bekleyen talep kapatılınca (CANCELLED) ve stok hâlâ kritikse yeniden öneri açılır", async () => {
    await prisma.stockPurchaseRequest.updateMany({
      where: { productId: withHistoryId, status: PurchaseRequestStatus.PENDING },
      data: { status: PurchaseRequestStatus.CANCELLED },
    });
    const id = await autoSuggestReplenishment(withHistoryId);
    expect(id).toBeTruthy();
    const total = await prisma.stockPurchaseRequest.count({ where: { productId: withHistoryId, isAutoGenerated: true } });
    expect(total).toBe(2);
  });
});
