import { Role, AdvanceStatus, JobStatus, PurchaseRequestStatus } from "@prisma/client";
import { prisma } from "./prisma";
import { notifyUser, notifyUsers, notifyManagement } from "./notify";
import { sendEmail } from "./email";
import { EXPIRY_ALERT_WINDOW_DAYS, findExpiringBatches } from "./productBatches";

const UPCOMING_JOB_WINDOW_START_MIN = 55;
const UPCOMING_JOB_WINDOW_END_MIN = 70;
const OVERDUE_PAYMENT_DAYS = 30;
const PENDING_APPROVAL_HOURS = 48;
const CONTRACT_EXPIRY_DAYS = 30;

interface UserForEmail {
  id: string;
  email: string;
}

async function shouldEmail(userId: string, field: "emailEnabled" | "dailyDigestEnabled" | "weeklyDigestEnabled"): Promise<boolean> {
  const preference = await prisma.notificationPreference.findUnique({ where: { userId } });
  if (!preference) return true; // no row yet — schema default is enabled
  return preference[field];
}

async function getOwners(): Promise<UserForEmail[]> {
  return prisma.user.findMany({ where: { role: Role.OWNER }, select: { id: true, email: true } });
}

async function notifyOwners(title: string, body: string, link?: Parameters<typeof notifyUsers>[3]): Promise<void> {
  const owners = await getOwners();
  await notifyUsers(owners.map((o) => o.id), title, body, link);

  for (const owner of owners) {
    if (await shouldEmail(owner.id, "emailEnabled")) {
      await sendEmail(owner.email, title, `<p>${body}</p>`);
    }
  }
}

function isSameCalendarDay(a: Date, b: Date): boolean {
  return a.toDateString() === b.toDateString();
}

interface LowStockProduct {
  id: string;
  name: string;
  unit: string;
  currentStock: unknown;
  criticalThreshold: unknown;
  lastLowStockAlertAt: Date | null;
}

/**
 * Bölüm A: hem işten hemen sonraki anlık kontrol (checkLowStockAndNotify) hem
 * de saatlik güvenlik ağı taraması (sweepLowStockAlerts) bu TEK fonksiyonu
 * kullanır — böylece iki tetikleyici asla aynı gün içinde çift bildirim
 * göndermez (lastLowStockAlertAt ile aynı gün kontrolü). Stok kritik eşiğin
 * üstüne çıkınca alan null'a döner ki bir sonraki düşüşte yeniden bildirim
 * gitsin.
 */
async function evaluateLowStockAlert(product: LowStockProduct): Promise<boolean> {
  const isCritical = Number(product.currentStock) <= Number(product.criticalThreshold);

  if (!isCritical) {
    if (product.lastLowStockAlertAt) {
      await prisma.product.update({ where: { id: product.id }, data: { lastLowStockAlertAt: null } });
    }
    return false;
  }

  // Bölüm AI (8. tur): kritikse tedarikçi geçmişine göre otomatik ikmal önerisi
  // (kendi PENDING dedup'ı var; günlük bildirim dedup'ından bağımsız).
  await autoSuggestReplenishment(product.id).catch((err) =>
    console.error("Otomatik ikmal önerisi başarısız:", err)
  );

  if (product.lastLowStockAlertAt && isSameCalendarDay(product.lastLowStockAlertAt, new Date())) {
    return false;
  }

  await notifyManagement(
    "Kritik stok uyarısı",
    `${product.name} stoğu kritik seviyenin altına düştü (${Number(product.currentStock)} ${product.unit} kaldı).`,
    { type: "low_stock", relatedType: "Product", relatedId: product.id }
  );
  await prisma.product.update({ where: { id: product.id }, data: { lastLowStockAlertAt: new Date() } });
  return true;
}

/**
 * Bölüm AI (8. tur): Otomatik stok yenileme önerisi.
 * Ürün kritik seviyedeyken:
 *  - daha önce kullanılan bir tedarikçi varsa (en son supplierId'li talep) ve
 *  - ürün için bekleyen (PENDING) talep yoksa
 * isAutoGenerated=true, PENDING bir StockPurchaseRequest açar (miktar: son talebin
 * miktarı). Tedarikçi geçmişi yoksa hiçbir şey yapmaz. requestedBy: ilk aktif OWNER.
 * Dönüş: oluşturulan talep id'si veya null.
 */
export async function autoSuggestReplenishment(productId: string): Promise<string | null> {
  const pending = await prisma.stockPurchaseRequest.findFirst({
    where: { productId, status: PurchaseRequestStatus.PENDING },
    select: { id: true },
  });
  if (pending) return null;

  const lastWithSupplier = await prisma.stockPurchaseRequest.findFirst({
    where: { productId, supplierId: { not: null } },
    orderBy: { createdAt: "desc" },
    select: { supplierId: true, quantity: true, supplier: { select: { name: true, isActive: true } } },
  });
  if (!lastWithSupplier?.supplierId) return null;

  const systemUser = await prisma.user.findFirst({
    where: { role: Role.OWNER, isActive: true },
    orderBy: { createdAt: "asc" },
    select: { id: true },
  });
  if (!systemUser) return null;

  const product = await prisma.product.findUnique({ where: { id: productId }, select: { name: true, unit: true } });
  if (!product) return null;

  const created = await prisma.stockPurchaseRequest.create({
    data: {
      productId,
      quantity: lastWithSupplier.quantity,
      supplierId: lastWithSupplier.supplierId,
      requestedByUserId: systemUser.id,
      isAutoGenerated: true,
      note: `Otomatik öneri: kritik stok — son tedarikçi ${lastWithSupplier.supplier?.name ?? ""}`.trim(),
    },
  });

  await notifyManagement(
    "Otomatik ikmal önerisi",
    `${product.name} kritik seviyede; ${lastWithSupplier.supplier?.name ?? "son tedarikçi"} için ` +
      `${Number(lastWithSupplier.quantity)} ${product.unit} öneri talebi açıldı.`,
    { type: "stock_purchase_request", relatedType: "Product", relatedId: productId }
  );
  return created.id;
}

/**
 * Checked right after a stock decrement (not on a cron tick) so OWNER/MANAGER hear about a
 * critical shortage the moment it happens, not up to an hour later.
 */
export async function checkLowStockAndNotify(productId: string): Promise<void> {
  const product = await prisma.product.findUnique({ where: { id: productId } });
  if (!product) return;
  await evaluateLowStockAlert(product);
}

/**
 * Saatlik güvenlik ağı (bkz. lib/cron.ts:startReminderCrons) — stok sayımı,
 * mal kabul gibi checkLowStockAndNotify'ı hiç TETİKLEMEYEN yollardan düşen
 * stokları da yakalar. Aynı gün içinde zaten bildirilmiş bir ürünü atlar.
 */
export async function sweepLowStockAlerts(onlyProductIds?: string[]): Promise<number> {
  // onlyProductIds: testler/manuel tetikleme için kapsam daraltıcı (Bölüm Q dersi).
  const products = await prisma.product.findMany(onlyProductIds ? { where: { id: { in: onlyProductIds } } } : undefined);
  let notifiedCount = 0;
  for (const product of products) {
    if (await evaluateLowStockAlert(product)) notifiedCount++;
  }
  return notifiedCount;
}

/** Every ~15 minutes: nudge staff whose job starts in about an hour. */
export async function sendUpcomingJobReminders(): Promise<number> {
  const now = new Date();
  const windowStart = new Date(now.getTime() + UPCOMING_JOB_WINDOW_START_MIN * 60 * 1000);
  const windowEnd = new Date(now.getTime() + UPCOMING_JOB_WINDOW_END_MIN * 60 * 1000);

  const jobs = await prisma.job.findMany({
    where: {
      scheduledAt: { gte: windowStart, lte: windowEnd },
      status: { in: [JobStatus.PENDING, JobStatus.SCHEDULED] },
      assignedStaffId: { not: null },
    },
    include: {
      customer: { select: { fullName: true } },
      assignedStaff: { include: { user: { select: { id: true, email: true } } } },
    },
  });

  for (const job of jobs) {
    const staffUser = job.assignedStaff?.user;
    if (!staffUser) continue;

    const timeLabel = job.scheduledAt!.toLocaleTimeString("tr-TR", { hour: "2-digit", minute: "2-digit" });
    const title = "Yaklaşan işiniz var";
    const body = `${job.serviceType} - ${job.customer.fullName} - ${timeLabel}`;

    await notifyUser(staffUser.id, title, body);
    if (await shouldEmail(staffUser.id, "emailEnabled")) {
      await sendEmail(staffUser.email, title, `<p>${body}</p>`);
    }
  }

  return jobs.length;
}

/** Daily: OWNER gets a summary of customers who owe money and haven't paid in a while. */
export async function sendOverduePaymentDigest(): Promise<number> {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - OVERDUE_PAYMENT_DAYS);

  const customers = await prisma.customer.findMany({
    include: {
      jobs: { select: { price: true } },
      payments: { select: { amount: true, createdAt: true }, orderBy: { createdAt: "desc" } },
    },
  });

  const overdue = customers
    .map((customer) => {
      const totalPriced = customer.jobs.reduce((sum, job) => sum + Number(job.price ?? 0), 0);
      const totalPaid = customer.payments.reduce((sum, payment) => sum + Number(payment.amount), 0);
      const outstandingBalance = totalPriced - totalPaid;
      const lastPaymentAt = customer.payments[0]?.createdAt ?? null;
      const isOverdue = lastPaymentAt ? lastPaymentAt < cutoff : true;
      return { customer, outstandingBalance, isOverdue };
    })
    .filter((row) => row.outstandingBalance > 0 && row.isOverdue);

  if (overdue.length === 0) return 0;

  const listHtml = overdue
    .map((row) => `<li>${row.customer.fullName} — ${row.outstandingBalance.toFixed(2)} TL</li>`)
    .join("");

  await notifyOwnersHtml(
    "Gecikmiş ödeme özeti",
    `${overdue.length} müşterinin 30 günden uzun süredir bekleyen bakiyesi var.`,
    `<p>${overdue.length} müşterinin 30 günden uzun süredir bekleyen bakiyesi var:</p><ul>${listHtml}</ul>`
  );

  return overdue.length;
}

/** Daily: OWNER gets nudged about advance/quote requests sitting unactioned for 48h+. */
export async function sendPendingApprovalReminders(): Promise<number> {
  const cutoff = new Date();
  cutoff.setHours(cutoff.getHours() - PENDING_APPROVAL_HOURS);

  const [pendingAdvances, pendingQuotes] = await Promise.all([
    prisma.advanceRequest.count({ where: { status: AdvanceStatus.PENDING, createdAt: { lte: cutoff } } }),
    prisma.quoteRequest.count({ where: { status: "NEW", createdAt: { lte: cutoff } } }),
  ]);

  const total = pendingAdvances + pendingQuotes;
  if (total === 0) return 0;

  await notifyOwners(
    "Bekleyen onaylar var",
    `${pendingAdvances} avans talebi ve ${pendingQuotes} teklif talebi 48 saatten uzun süredir yanıt bekliyor.`
  );

  return total;
}

/** Daily: OWNER + MANAGER get notified about contracts expiring within 30 days. */
export async function sendContractExpiryReminders(): Promise<number> {
  const now = new Date();
  const in30Days = new Date();
  in30Days.setDate(now.getDate() + CONTRACT_EXPIRY_DAYS);

  const contracts = await prisma.contract.findMany({
    where: { endDate: { gte: now, lte: in30Days } },
    include: { customer: { select: { fullName: true } } },
  });

  if (contracts.length === 0) return 0;

  const managers = await prisma.user.findMany({
    where: { role: { in: [Role.OWNER, Role.MANAGER] } },
    select: { id: true, email: true },
  });

  const title = "Yaklaşan sözleşme bitişleri";
  const body = `${contracts.length} sözleşme önümüzdeki 30 gün içinde sona eriyor.`;

  await notifyUsers(managers.map((m) => m.id), title, body);
  for (const manager of managers) {
    if (await shouldEmail(manager.id, "emailEnabled")) {
      await sendEmail(manager.email, title, `<p>${body}</p>`);
    }
  }

  return contracts.length;
}

/** Daily: OWNER gets notified about staff certifications expiring within 30 days. */
export async function sendCertificationExpiryReminders(): Promise<number> {
  const now = new Date();
  const in30Days = new Date();
  in30Days.setDate(now.getDate() + CONTRACT_EXPIRY_DAYS);

  const certifications = await prisma.staffCertification.findMany({
    where: { expiryDate: { gte: now, lte: in30Days } },
  });

  if (certifications.length === 0) return 0;

  await notifyOwners(
    "Yaklaşan sertifika bitişleri",
    `${certifications.length} personel sertifikası önümüzdeki 30 gün içinde sona eriyor.`
  );

  return certifications.length;
}

async function notifyOwnersHtml(title: string, plainBody: string, html: string): Promise<void> {
  const owners = await getOwners();
  await notifyUsers(owners.map((o) => o.id), title, plainBody);

  for (const owner of owners) {
    if (await shouldEmail(owner.id, "emailEnabled")) {
      await sendEmail(owner.email, title, html);
    }
  }
}

/** 07:00 daily digest email for OWNER(s) with dailyDigestEnabled. */
export async function sendDailyDigest(): Promise<number> {
  const owners = await getOwners();
  const eligibleOwners: UserForEmail[] = [];
  for (const owner of owners) {
    if (await shouldEmail(owner.id, "dailyDigestEnabled")) {
      eligibleOwners.push(owner);
    }
  }
  if (eligibleOwners.length === 0) return 0;

  const now = new Date();
  const startOfDay = new Date(now);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(now);
  endOfDay.setHours(23, 59, 59, 999);
  const cutoff = new Date();
  cutoff.setHours(cutoff.getHours() - PENDING_APPROVAL_HOURS);

  const [todaysJobsCount, newQuotesCount, pendingAdvances, pendingQuotes, products] = await Promise.all([
    prisma.job.count({ where: { scheduledAt: { gte: startOfDay, lte: endOfDay } } }),
    prisma.quoteRequest.count({ where: { status: "NEW" } }),
    prisma.advanceRequest.count({ where: { status: AdvanceStatus.PENDING } }),
    prisma.quoteRequest.count({ where: { status: "NEW", createdAt: { lte: cutoff } } }),
    prisma.product.findMany(),
  ]);

  const criticalProducts = products.filter((p) => Number(p.currentStock) <= Number(p.criticalThreshold));

  const dateLabel = now.toLocaleDateString("tr-TR", { day: "numeric", month: "long", year: "numeric" });

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 560px;">
      <h2 style="color: #1F5C3D;">Nilüfer İlaçlama - Bugünün Özeti</h2>
      <p style="color: #555;">${dateLabel}</p>
      <table style="width: 100%; border-collapse: collapse; margin-top: 16px;">
        <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;">Bugünkü iş sayısı</td><td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right; font-weight: bold;">${todaysJobsCount}</td></tr>
        <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;">Yeni teklif talebi</td><td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right; font-weight: bold;">${newQuotesCount}</td></tr>
        <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;">Bekleyen avans talebi</td><td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right; font-weight: bold;">${pendingAdvances}</td></tr>
        <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;">48 saatten eski bekleyen teklif</td><td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right; font-weight: bold;">${pendingQuotes}</td></tr>
      </table>
      ${
        criticalProducts.length > 0
          ? `<h3 style="color: #B3261E; margin-top: 20px;">Kritik stok uyarıları</h3>
             <ul>${criticalProducts.map((p) => `<li>${p.name} — ${Number(p.currentStock)} ${p.unit}</li>`).join("")}</ul>`
          : `<p style="margin-top: 20px; color: #1F5C3D;">Kritik stok uyarısı yok.</p>`
      }
    </div>
  `;

  for (const owner of eligibleOwners) {
    await sendEmail(owner.email, `Bugünün Özeti - ${dateLabel}`, html);
  }

  return eligibleOwners.length;
}

const RENEWAL_ALERT_WINDOW_DAYS = 7;

/**
 * Bölüm B (2. tur): mevcut `sendContractExpiryReminders` 30 günlük genel bir
 * bilgilendirme özeti (toplam sayı, günde bir kez 08:00'de zaten çalışıyor).
 * Bu fonksiyon AYRI ve daha aciliyetli — bitişine 7 gün veya daha az kalan
 * HER sözleşme için ayrı ayrı, sözleşme bazlı `lastRenewalAlertAt` ile
 * günlük dedup'lı bir hatırlatma gönderir. İkisi birbirinin yerini almaz,
 * tamamlayıcıdır (30 gün = "haberin olsun", 7 gün = "acele et").
 */
/** 7 günlük yenileme penceresi — sweep ve yönetici özeti aynı filtreyi paylaşır. */
export function contractRenewalWindowWhere(now = new Date()) {
  const windowEnd = new Date(now);
  windowEnd.setDate(windowEnd.getDate() + RENEWAL_ALERT_WINDOW_DAYS);
  return { status: "ACTIVE", endDate: { gte: now, lte: windowEnd } };
}

export async function sweepContractRenewalAlerts(): Promise<number> {
  const now = new Date();

  const contracts = await prisma.contract.findMany({
    where: contractRenewalWindowWhere(now),
    include: { customer: { select: { fullName: true } } },
  });

  let notifiedCount = 0;
  for (const contract of contracts) {
    if (contract.lastRenewalAlertAt && isSameCalendarDay(contract.lastRenewalAlertAt, now)) continue;

    const daysLeft = Math.max(0, Math.ceil((contract.endDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
    await notifyManagement(
      "Sözleşme yenileme hatırlatması",
      `${contract.customer.fullName} sözleşmesi ${daysLeft} gün içinde sona eriyor.`,
      { type: "contract_renewal", relatedType: "Contract", relatedId: contract.id }
    );
    await prisma.contract.update({ where: { id: contract.id }, data: { lastRenewalAlertAt: now } });
    notifiedCount++;
  }

  return notifiedCount;
}

/**
 * Bölüm AM (9. tur): SKT'si 7 gün içinde dolacak veya dolmuş, bakiyesi > 0
 * partiler için yönetime (OWNER/MANAGER) günlük dedup'lı bildirim —
 * `ProductBatch.lastExpiryAlertAt` ile aynı takvim günü kontrolü
 * (lastLowStockAlertAt deseni). Bakiyesi sıfırlanan parti listeden düşer.
 * @param onlyProductIds Testler/manuel tetikleme için kapsam daraltıcı —
 *   üretimde verilmez (bkz. lib/cron.ts).
 */
export async function sweepExpiringBatchAlerts(onlyProductIds?: string[]): Promise<number> {
  const now = new Date();
  const batches = await findExpiringBatches(EXPIRY_ALERT_WINDOW_DAYS, onlyProductIds);

  let notifiedCount = 0;
  for (const batch of batches) {
    if (batch.lastExpiryAlertAt && isSameCalendarDay(batch.lastExpiryAlertAt, now)) continue;

    const body = batch.isExpired
      ? `${batch.product.name} · Parti ${batch.batchNumber} son kullanma tarihi GEÇTİ (${Number(batch.quantityRemaining)} ${batch.product.unit} kaldı). İmha/iade edilmeli.`
      : `${batch.product.name} · Parti ${batch.batchNumber} ${batch.daysLeft} gün içinde son kullanma tarihine ulaşıyor (${Number(batch.quantityRemaining)} ${batch.product.unit} kaldı).`;

    await notifyManagement(
      batch.isExpired ? "Süresi dolmuş kimyasal partisi" : "Son kullanma tarihi yaklaşan parti",
      body,
      { type: "batch_expiry", relatedType: "Product", relatedId: batch.productId }
    );
    await prisma.productBatch.update({ where: { id: batch.id }, data: { lastExpiryAlertAt: now } });
    notifiedCount++;
  }

  return notifiedCount;
}
