// Bölüm AI (8. tur): otomatik ikmal önerisi bayrağı ayrıştırma testi.

import 'package:flutter_test/flutter_test.dart';

import 'package:nilufer_mobile/models/product.dart';

void main() {
  final base = {
    'id': 'pr1',
    'productId': 'p1',
    'quantity': '25.00',
    'status': 'PENDING',
    'createdAt': '2026-09-18T08:00:00.000Z',
    'product': {'id': 'p1', 'name': 'İlaç', 'unit': 'L'},
    'supplier': {'id': 's1', 'name': 'Tedarikçi A'},
  };

  test('isAutoGenerated true okunur', () {
    final r = StockPurchaseRequest.fromJson({...base, 'isAutoGenerated': true});
    expect(r.isAutoGenerated, isTrue);
    expect(r.supplierName, 'Tedarikçi A');
    expect(r.quantity, 25.0);
  });

  test('alan yoksa varsayılan false (eski kayıtlar)', () {
    expect(StockPurchaseRequest.fromJson(base).isAutoGenerated, isFalse);
  });
}
